name: mediboard
description: My take home assessment from Really Great Tech
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animations: ^2.0.10
  async: ^2.11.0
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  collection: ^1.18.0
  dots_indicator: ^3.0.0
  fast_immutable_collections: ^9.2.0
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  multiple_result: ^5.1.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  stack_trace: ^1.11.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/json/
    - assets/icons/
    - assets/icons/large/
    - assets/icons/small/
